export const VILLAGE_STATUS: {
  PROLOGUE: string
  PROGRESS: string
  EPILOGUE: string
  COMPLETE: string
  CANCEL: string
} = {
  PROLOGUE: 'PROLOGUE',
  PROGRESS: 'IN_PROGRESS',
  EPILOGUE: 'EPILOGUE',
  COMPLETE: 'COMPLETED',
  CANCEL: 'CANCEL'
}

export const MESSAGE_TYPE: {
  PUBLIC_SYSTEM: string
  PRIVATE_SYSTEM: string
  PRIVATE_SEER: string
  PRIVATE_WISE: string
  PRIVATE_PSYCHIC: string
  PRIVATE_GURU: string
  PRIVATE_WEREWOLF: string
  PRIVATE_FANATIC: string
  PRIVATE_MASON: string
  PRIVATE_FOX: string
  PRIVATE_SYMPATHIZER: string
  PRIVATE_CORONER: string
  PRIVATE_LOVERS: string
  PRIVATE_ABILITY: string
  NORMAL_SAY: string
  MONOLOGUE_SAY: string
  GRAVE_SAY: string
  WEREWOLF_SAY: string
  SYMPATHIZE_SAY: string
  LOVERS_SAY: string
  SPECTATE_SAY: string
  CREATOR_SAY: string
  SECRET_SAY: string
  PARTICIPANTS: string
  ACTION: string
} = {
  PUBLIC_SYSTEM: 'PUBLIC_SYSTEM',
  PRIVATE_SYSTEM: 'PRIVATE_SYSTEM',
  PRIVATE_SEER: 'PRIVATE_SEER',
  PRIVATE_WISE: 'PRIVATE_WISE',
  PRIVATE_PSYCHIC: 'PRIVATE_PSYCHIC',
  PRIVATE_GURU: 'PRIVATE_GURU',
  PRIVATE_WEREWOLF: 'PRIVATE_WEREWOLF',
  PRIVATE_FANATIC: 'PRIVATE_FANATIC',
  PRIVATE_MASON: 'PRIVATE_MASON',
  PRIVATE_FOX: 'PRIVATE_FOX',
  PRIVATE_SYMPATHIZER: 'PRIVATE_SYMPATHIZER',
  PRIVATE_CORONER: 'PRIVATE_CORONER',
  PRIVATE_LOVERS: 'PRIVATE_LOVERS',
  PRIVATE_ABILITY: 'PRIVATE_ABILITY',
  NORMAL_SAY: 'NORMAL_SAY',
  MONOLOGUE_SAY: 'MONOLOGUE_SAY',
  GRAVE_SAY: 'GRAVE_SAY',
  WEREWOLF_SAY: 'WEREWOLF_SAY',
  SYMPATHIZE_SAY: 'SYMPATHIZE_SAY',
  LOVERS_SAY: 'LOVERS_SAY',
  SPECTATE_SAY: 'SPECTATE_SAY',
  CREATOR_SAY: 'CREATOR_SAY',
  SECRET_SAY: 'SECRET_SAY',
  PARTICIPANTS: 'PARTICIPANTS',
  ACTION: 'ACTION'
}

export const FACE_TYPE: {
  NORMAL: string
  WEREWOLF: string
  GRAVE: string
  MONOLOGUE: string
  MASON: string
  SECRET: string
  LOVER: string
} = {
  NORMAL: 'NORMAL',
  WEREWOLF: 'WEREWOLF',
  GRAVE: 'GRAVE',
  MONOLOGUE: 'MONOLOGUE',
  MASON: 'MASON',
  SECRET: 'SECRET',
  LOVER: 'LOVER'
}
